// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1fyWwxbpbaiGlis5FShm5mlNN4mH6-Y',
    appId: '1:693159993831:web:dae4e3c3f2aa7bda429d42',
    messagingSenderId: '693159993831',
    projectId: 'mohamedchat-e5973',
    authDomain: 'mohamedchat-e5973.firebaseapp.com',
    storageBucket: 'mohamedchat-e5973.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv74LmVYm11ACfdOXDJB9feQXc2zcJbs4',
    appId: '1:693159993831:android:ab0d6f812a3d5ab5429d42',
    messagingSenderId: '693159993831',
    projectId: 'mohamedchat-e5973',
    storageBucket: 'mohamedchat-e5973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFFYlz_vCN7rk5_4haOafYL39RuVvUhU',
    appId: '1:693159993831:ios:48f6cf18309b254b429d42',
    messagingSenderId: '693159993831',
    projectId: 'mohamedchat-e5973',
    storageBucket: 'mohamedchat-e5973.appspot.com',
    iosBundleId: 'com.example.mohamedChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFFYlz_vCN7rk5_4haOafYL39RuVvUhU',
    appId: '1:693159993831:ios:48f6cf18309b254b429d42',
    messagingSenderId: '693159993831',
    projectId: 'mohamedchat-e5973',
    storageBucket: 'mohamedchat-e5973.appspot.com',
    iosBundleId: 'com.example.mohamedChat',
  );
}
